export const ActionTypes = {
  SET_ACCOUNTS: "SET_ACCOUNTS",
  SET_COMPANY: "SET_COMPANY",
  SELECTED_ACCOUNT: "SELECTED_ACCOUNT",
  REMOVE_SELECTED_ACCOUNT: "REMOVE_SELECTED_ACCOUNT",
  SET_USER_DETAILS: "SET_USER_DETAILS",
}
